#
# Skills list for BRP based games
#

def skill_bases():

    skill_dict = {
        'Appraise' : 15,
        'Art' : 5,
        'Artillery' : 0,
        'Bargain' :  5,
        'Brawl' : 25,
        'Climb' : 40,
        'Command' : 5,
        'Craft'  : 5,
        'Demolition' : 1,
        'Disguise' : 1,
        'Dodge' : $xstats[5] * 2,
        'Drive Common' : 20,
        'Drive Rare' : 1,
        'Energy Weapon' : 0,
        'Etiquette' : 5,
        'Fast Talk' : 5,
        'Fine Manipulation' : 5,
        'Firearm' : 0,
        'First Aid' : 30,
        'Fly Gear' : $xstats[5] / 2,
        'Fly Wings' : $xstats[5] * 4,
        'Gaming' : $xstats[3] + $xstats[4],
        'Grapple' : 25,
        'Heavy Machine'  : 1,
        'Heavy Weapon'  : 0,
        'Hide' : 10,
        'Insight' : 5,
        'Jump' : 25,
        'Knowledge Common'  : 5,
        'Knowledge Rare'  : 1,
        'Language Other' : 0,
        'Language Own' : 0,
        'Listen' : 25,
        'Literacy INT' : $xstats[3] * 4,
        'Literacy EDU' : $xstats[4] * 4,
        'Martial Arts' : 01,
        'Medicine Modern' : 5,
        'Medicine Ancient' : 0,
        'Melee Weapon' :  0,
        'Missile Weapon' :  0,
        'Navigate' : 10,
        'Parry'  : 0,
        'Perform'  : 5,
        'Persuade' : 15,
        'Pilot'  : 1,
        'Projection' : $xstats[5] * 2,
        'Psychotherapy Common' : 1,
        'Psychotherapy Rare' : 0,
        'Repair' :  15,
        'Research' : 25,
        'Ride' :  5,
        'Science' : 1,
        'Sense' :  10,
        'Shield' : 0,
        'Sleight of Hand' : 5,
        'Spot' : 25,
        'Status' : 15,
        'Stealth' : 10,
        'Strategy' : 01,
        'Swim' : 25,
        'Teach' : 10,
        'Technical Skill Ancient' :  0,
        'Technical Skill Rare' :  1,
        'Technical Skill Common' :  5,
        'Throw' : 25,
        'Track' : 10
}

