#
# Skills list for Call of Cthulhu based games
#

def coc_skill_bases():

    coc_1990s_skill_dict = {
       'Accounting' : 10,
       'Anthropology' : 0,
       'Archaeology' : 0,
       'Art' : 5,
       'Astronomy' : 0,
       'Bargain' : 5,
       'Biology' : 0,
       'Chemistry' : 0,
       'Climb' : 40,
       'Computer Use' : 0,
       'Conceal' : 15,
       'Credit Rating' : 15,
       'Cthulhu Mythos' : 0,
       'Dodge' : self.statblock["DEX"] * 2,
       'Drive Auto' : 20,
       'Electrical Repair' : 10,
       'Electronics' : 0,
       'Fast Talk' : 5,
       'Firearms Handgun' : 20,
       'Firearms Machine Gun' : 15,
       'Firearms Rifle' : 25,
       'Firearms Shotgun' : 30,
       'Firearms Submachine Gun' : 15,
       'First Aid' : 30,
       'Fist-Punch' : 50,
       'Geology' : 0,
       'Grapple' : 25,
       'Head Butt' : 10,
       'Hide' : 10,
       'History' : 20,
       'Jump' : 25,
       'Kick' : 25,
       'Law' : 5,
       'Library Use' : 25,
       'Listen' : 25,
       'Locksmith' : 0,
       'Martial Arts' : 0,
       'Mechanical Repair' : 20,
       'Medicine' : 5,
       'Natural History' : 10,
       'Navigate' : 10,
       'Occult' : 5,
       'Operate Heavy Machinery' : 0,
       'Other Language' : 0,
       'Own Language' : self.statblock["EDU"] * 5,
       'Persuade' : 15,
       'Pharmacy' : 0,
       'Photography' : 10,
       'Physics' : 0,
       'Pilot' : 0,
       'Psychoanalysis' : 0,
       'Psychology' : 5,
       'Ride' : 5,
       'Sneak' : 10,
       'Spot Hidden' : 25,
       'Swim' : 25,
       'Throw' : 25,
       'Track' : 10
}
    coc_1920s_skill_dict = {
       'Accounting' : 10,
       'Anthropology' : 0,
       'Archaeology' : 0,
       'Art' : 5,
       'Astronomy' : 0,
       'Bargain' : 5,
       'Biology' : 0,
       'Chemistry' : 0,
       'Climb' : 40,
       'Conceal' : 15,
       'Credit Rating' : 15,
       'Cthulhu Mythos' : 0,
       'Dodge' : self.statblock["DEX"] * 2,
       'Drive Auto' : 20,
       'Electrical Repair' : 10,
       'Fast Talk' : 5,
       'Firearms Handgun' : 20,
       'Firearms Machine Gun' : 15,
       'Firearms Rifle' : 25,
       'Firearms Shotgun' : 30,
       'Firearms Submachine Gun' : 15,
       'First Aid' : 30,
       'Fist-Punch' : 50,
       'Geology' : 0,
       'Grapple' : 25,
       'Head Butt' : 10,
       'Hide' : 10,
       'History' : 20,
       'Jump' : 25,
       'Kick' : 25,
       'Law' : 5,
       'Library Use' : 25,
       'Listen' : 25,
       'Locksmith' : 0,
       'Martial Arts' : 0,
       'Mechanical Repair' : 20,
       'Medicine' : 5,
       'Natural History' : 10,
       'Navigate' : 10,
       'Occult' : 5,
       'Operate Heavy Machinery' : 0,
       'Other Language' : 0,
       'Own Language' : self.statblock["EDU"] * 5,
       'Persuade' : 15,
       'Pharmacy' : 0,
       'Photography' : 10,
       'Physics' : 0,
       'Pilot' : 0,
       'Psychoanalysis' : 0,
       'Psychology' : 5,
       'Ride' : 5,
       'Sneak' : 10,
       'Spot Hidden' : 25,
       'Swim' : 25,
       'Throw' : 25,
       'Track' : 10
}
    coc_1890s_skill_dict = {
       'Accounting' : 10,
       'Anthropology' : 0,
       'Archaeology' : 0,
       'Art' : 5,
       'Astronomy' : 0,
       'Bargain' : 5,
       'Biology' : 0,
       'Chemistry' : 0,
       'Climb' : 40,
       'Conceal' : 15,
       'Credit Rating' : 15,
       'Cthulhu Mythos' : 0,
       'Dodge' : self.statblock["DEX"] * 2,
       'Drive Carriage' : 20,
       'Electrical Repair' : 10,
       'Electronics' : 0,
       'Fast Talk' : 5,
       'Firearms Handgun' : 20,
       'Firearms Machine Gun' : 15,
       'Firearms Rifle' : 25,
       'Firearms Shotgun' : 30,
       'Firearms Submachine Gun' : 15,
       'First Aid' : 30,
       'Fist-Punch' : 50,
       'Geology' : 0,
       'Grapple' : 25,
       'Head Butt' : 10,
       'Hide' : 10,
       'History' : 20,
       'Jump' : 25,
       'Kick' : 25,
       'Law' : 5,
       'Library Use' : 25,
       'Listen' : 25,
       'Locksmith' : 0,
       'Martial Arts' : 0,
       'Mechanical Repair' : 20,
       'Medicine' : 5,
       'Natural History' : 10,
       'Navigate' : 10,
       'Occult' : 5,
       'Operate Heavy Machinery' : 0,
       'Other Language' : 0,
       'Own Language' : self.statblock["EDU"] * 5,
       'Persuade' : 15,
       'Pharmacy' : 0,
       'Photography' : 10,
       'Physics' : 0,
       'Pilot Balloon' : 0,
       'Pilot Boat' : 0,
       'Psychology' : 5,
       'Ride' : 5,
       'Sneak' : 10,
       'Spot Hidden' : 25,
       'Swim' : 25,
       'Throw' : 25,
       'Track' : 10
}
